// faq的文本
    const  faq = [
      {
        title: "Has yourclient used credit before?",
        content:`A MIC pools investor funds to offer short-term financing 6-36 months) backed by real estate. The interest and fees paid by borrowers, net of operating costs, are passed on to investors. Due  to the current low interest rate environment, investors seeking higher yields are drawn to the MIC space. 

Profits generated by MICs are distributed to its shareholders according to their proportionalinterest. The mortgages are secured primarily on real property, but can be in conjunction with other forms of security such as: personal and corporate guarantees, general security agreements, and assignments of material contracts (ie. insurance policies prepared by lawyers for the MIC)
       
Owning shares in a mortgage investment corporation means you are investing in a company which manages a diversified and secured group of mortgages. Shares of a MIC arequalified investments under the Income Tax Act 130.1(Canada) for RRSP, RRIF, TFSA, RESP and more.`
      },
      {
        title: "Do they pay their bills on time?",
        content:`A MIC pools investor funds to offer short-term financing 6-36 months) backed by real estate. The interest and fees paid by borrowers, net of operating costs, are passed on to investors. Due  to the current low interest rate environment, investors seeking higher yields are drawn to the MIC space. 

Profits generated by MICs are distributed to its shareholders according to their proportionalinterest. The mortgages are secured primarily on real property, but can be in conjunction with other forms of security such as: personal and corporate guarantees, general security agreements, and assignments of material contracts (ie. insurance policies prepared by lawyers for the MIC)
       
Owning shares in a mortgage investment corporation means you are investing in a company which manages a diversified and secured group of mortgages. Shares of a MIC arequalified investments under the Income Tax Act 130.1(Canada) for RRSP, RRIF, TFSA, RESP and more.`
      },
      {
        title: "Does your client have a good credit report?",
        content:`A MIC pools investor funds to offer short-term financing 6-36 months) backed by real estate. The interest and fees paid by borrowers, net of operating costs, are passed on to investors. Due  to the current low interest rate environment, investors seeking higher yields are drawn to the MIC space. 

Profits generated by MICs are distributed to its shareholders according to their proportionalinterest. The mortgages are secured primarily on real property, but can be in conjunction with other forms of security such as: personal and corporate guarantees, general security agreements, and assignments of material contracts (ie. insurance policies prepared by lawyers for the MIC)
       
Owning shares in a mortgage investment corporation means you are investing in a company which manages a diversified and secured group of mortgages. Shares of a MIC arequalified investments under the Income Tax Act 130.1(Canada) for RRSP, RRIF, TFSA, RESP and more.`
      },
      {
        title: "How long have they lived at their present address?",
        content:`A MIC pools investor funds to offer short-term financing 6-36 months) backed by real estate. The interest and fees paid by borrowers, net of operating costs, are passed on to investors. Due  to the current low interest rate environment, investors seeking higher yields are drawn to the MIC space. 
Profits generated by MICs are distributed to its shareholders according to their proportionalinterest. The mortgages are secured primarily on real property, but can be in conjunction with other forms of security such as: personal and corporate guarantees, general security agreements, and assignments of material contracts (ie. insurance policies prepared by lawyers for the MIC)
       
Owning shares in a mortgage investment corporation means you are investing in a company which manages a diversified and secured group of mortgages. Shares of a MIC arequalified investments under the Income Tax Act 130.1(Canada) for RRSP, RRIF, TFSA, RESP and more.`
      },
      {
        title: "How long have they been at their present job?",
        content:`A MIC pools investor funds to offer short-term financing 6-36 months) backed by real estate. The interest and fees paid by borrowers, net of operating costs, are passed on to investors. Due  to the current low interest rate environment, investors seeking higher yields are drawn to the MIC space. 

Profits generated by MICs are distributed to its shareholders according to their proportionalinterest. The mortgages are secured primarily on real property, but can be in conjunction with other forms of security such as: personal and corporate guarantees, general security agreements, and assignments of material contracts (ie. insurance policies prepared by lawyers for the MIC)
       
Owning shares in a mortgage investment corporation means you are investing in a company which manages a diversified and secured group of mortgages. Shares of a MIC arequalified investments under the Income Tax Act 130.1(Canada) for RRSP, RRIF, TFSA, RESP and more.`
      },
    ]

export default faq